name: rancher-traefik
description: |
  Traefik service connecting to Cattle orchestrator for dynamic configuration
version: 1.3.0.0
category: Load balancing
maintainer: "MichaelChampagne <mch1307@gmail.com>"
license:
projectURL: https://github.com/mch1307/rancher-traefik