name: rancher-traefik
description: |
  # Traefik service connecting to Cattle orchestrator for dynamicconfiguration
version: 0.0
category: Load balancing
maintainer: "MichaelChampagne <mch1307@gmail.com>
license:
projectURL: https://github.com/mch1307/rancher-traefik