version: '2'
services:
  traefik:
    image: mch1307/rancher-traefik:1.3.0-1
    environment:
      TRAEFIK_RANCHER_ACCESSKEY: ${rancher_api_key}
      TRAEFIK_RANCHER_SECRET: ${rancher_api_secret}
      TRAEFIK_SSL_CERT: ${ssl_cert}
      TRAEFIK_SSL_PRIVATE_KEY: ${ssl_key}
      TRAEFIK_RANCHER_ENDPOINT: ${rancher_api}
      TRAEFIK_RANCHER_DOMAIN: ${traefik_domain}
      TRAEFIK_REFRESH: ${refresh_interval}
    ports:
    - ${http_port}:80/tcp
    - ${https_port}:443/tcp
    - ${admin_port}:8000/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: ${host_label}
